# ReGreet configuration
# See README at https://github.com/rharish101/ReGreet#configuration

[background]
# Path to the background image
path = "/usr/share/endeavouros/backgrounds/endeavouros-wallpaper.png"

# How the background image covers the screen if the aspect ratio doesn't match
# Available values: "Fill", "Contain", "Cover", "ScaleDown"
# Refer to: https://docs.gtk.org/gtk4/enum.ContentFit.html
# NOTE: This is ignored if ReGreet isn't compiled with GTK v4.8 support.
fit = "Cover"

# The entries defined in this section will be passed to the session as environment variables when it is started
[env]
# Set desktop and session type
XDG_SESSION_TYPE = "wayland"
XDG_CURRENT_DESKTOP = "sway"
XDG_SESSION_DESKTOP = "sway"

# Specify Wayland backends for various applications
MOZ_ENABLE_WAYLAND = "1"
OZONE_PLATFORM = "wayland"
GDK_BACKEND = "wayland"
QT_QPA_PLATFORM = "wayland"

# Prevent using hardware cursors in Wayland, forcing software-rendered cursors.
# Uncomment if you experience issues with your cursor
#WLR_NO_HARDWARE_CURSORS = "1"

# Allow the Wayland renderer to fall back to software rendering if necessary.
# Uncomment if you are running in a virtual machine or have an underpowered GPU
#WLR_RENDERER_ALLOW_SOFTWARE = "1"

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "Adwaita"

# Font name and size
font_name = "Cantarell 12"

# Icon theme name
icon_theme_name = "Adwaita"

# GTK theme name
theme_name = "Adwaita"

[commands]
# The command used to reboot the system
reboot = [ "systemctl", "reboot" ]

# The command used to shut down the system
poweroff = [ "systemctl", "poweroff" ]

[appearance]
# The message that initially displays on startup
greeting_msg = "Welcome Back!"
